# Task
# Available Task: [Segmentation3DTask]
task: 'Segmentation3DTask'

# General Setting - log path
exp_name: "conv_next_1.3.2_lidar"
save_dir: "/deep2/u/yma42/files/results/seg3d"
version: 7

# General Setting - GPU
gpus: 10
strategy: "ddp"

# General setting - data parameter
num_cls: 23
loader_worker: 16
train_path: '/scr/data/h5/train.h5'
val_path: '/scr/data/h5/validate.h5'
test_path: '/scr/data/h5/test.h5'
key_to_load: ['range_image', 'ri1_label']

# General setting - model
encoder: ConvNeXt
encoder_parm: {num_inchannel: 6}
decoder: ConvNeXt
decoder_parm: {}
head: Salsa
head_parm: {num_features: 32, num_cls: 23}

# loss
lavasz_softmax: True
poly1_Xentropy: False
poly1_eps: 0.5
weighted_Xentropy: True
class_weight_eps: 0.001

# General setting - training parameter
batch_size: 4
max_epochs: 100

# lr warmup/decay
learning_rate: 0.005
peak_learning_rate: 0.005
final_learning_rate: 0
lr_warmup_batch: 2965
lr_constant_batch: 2965
lr_decay_batch: 59300
decay_type: 'cos'
cos_Tmult: 2

# General setting - lightning specific 
gradient_clip_val: 0.5
enable_model_summary: False
limit_train_batches: 1.0
monitor_metric: "Val/epoch_avg_mIoU"
monitor_mode: "max"
save_top_k: 5
patience: 15